### ISSUE TITLE
rubydoc.info doesn't quite like README.md

### ISSUE THREAD

**Issue by swolchok** [rmosolgo/graphql-libgraphqlparser-ruby#19]
http://www.rubydoc.info/gems/graphql-libgraphqlparser/0.5.1 (which I got to from https://rubygems.org/gems/graphql-libgraphqlparser) doesn't seem to be rendering README.md quite faithfully. For example, the benchmark results are cut off. Screenshot attached. 

![image](https://cloud.githubusercontent.com/assets/34168/19660064/48b491e8-99e3-11e6-813e-a38d210f7f16.png)

**Comment by rmosolgo** [comment]
lol wat

**Comment by rmosolgo** [comment]
I wonder if a `.yardopts` will help. Also ... that benchmark is old! The new Ruby parser is not so bad :P

**Comment by rmosolgo** [comment]
Fixed with a new gem version, whose bundle includes `.yardopts`. Thanks for reporting this!

http://www.rubydoc.info/gems/graphql-libgraphqlparser/1.0.0

![image](https://cloud.githubusercontent.com/assets/2231765/19751872/a6ae27ca-9bc6-11e6-8dd1-753de1ebc374.png)
